/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "",
  "description": "",
  "base": "/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/favicon.ico"
      }
    ],
    [
      "link",
      {
        "rel": "manifest",
        "href": "/manifest.json"
      }
    ],
    [
      "meta",
      {
        "name": "theme-color",
        "content": "#3eaf7c"
      }
    ],
    [
      "meta",
      {
        "name": "apple-mobile-web-app-capable",
        "content": "yes"
      }
    ],
    [
      "meta",
      {
        "name": "apple-mobile-web-app-status-bar-style",
        "content": "black"
      }
    ],
    [
      "link",
      {
        "rel": "apple-touch-icon",
        "href": "/icons/apple-touch-icon-152x152.png"
      }
    ],
    [
      "meta",
      {
        "name": "msapplication-TileColor",
        "content": "#000000"
      }
    ]
  ],
  "pages": [
    {
      "title": "User Guide",
      "frontmatter": {},
      "regularPath": "/guide/",
      "relativePath": "guide/README.md",
      "key": "v-4c478294",
      "path": "/guide/",
      "headers": [
        {
          "level": 2,
          "title": "Step 1: Registration and Profile Completion",
          "slug": "step-1-registration-and-profile-completion"
        },
        {
          "level": 2,
          "title": "Step 2: Browsing Events",
          "slug": "step-2-browsing-events"
        },
        {
          "level": 2,
          "title": "Step 3: Register for Participation",
          "slug": "step-3-register-for-participation"
        },
        {
          "level": 2,
          "title": "Step 4: Event Management",
          "slug": "step-4-event-management"
        },
        {
          "level": 2,
          "title": "Q&A",
          "slug": "q-a"
        }
      ]
    },
    {
      "title": "Getting Started",
      "frontmatter": {},
      "regularPath": "/guide/getting-started.html",
      "relativePath": "guide/getting-started.md",
      "key": "v-0aaaf70d",
      "path": "/guide/getting-started.html",
      "headers": [
        {
          "level": 2,
          "title": "TODO",
          "slug": "todo"
        },
        {
          "level": 3,
          "title": "TODO",
          "slug": "todo-2"
        }
      ]
    },
    {
      "frontmatter": {
        "home": false,
        "heroImage": null,
        "heroText": null,
        "tagline": null
      },
      "regularPath": "/zh/",
      "relativePath": "zh/README.md",
      "key": "v-26ffeae4",
      "path": "/zh/"
    },
    {
      "title": "!BeWater",
      "frontmatter": {},
      "regularPath": "/zh/aixcrypto/chapter3.html",
      "relativePath": "zh/aixcrypto/chapter3.md",
      "key": "v-61ffa298",
      "path": "/zh/aixcrypto/chapter3.html",
      "headers": [
        {
          "level": 2,
          "title": "TODO",
          "slug": "todo"
        },
        {
          "level": 3,
          "title": "TODO",
          "slug": "todo-2"
        }
      ]
    },
    {
      "frontmatter": {
        "home": false,
        "heroImage": null,
        "heroText": null,
        "tagline": null
      },
      "regularPath": "/",
      "relativePath": "index.md",
      "key": "v-9608441a",
      "path": "/"
    },
    {
      "title": "人工智能 x 密码的核心框架",
      "frontmatter": {},
      "regularPath": "/zh/aixcrypto/chapter1.html",
      "relativePath": "zh/aixcrypto/chapter1.md",
      "key": "v-bc762618",
      "path": "/zh/aixcrypto/chapter1.html",
      "headers": [
        {
          "level": 2,
          "title": "2-1 介绍性案例、研究",
          "slug": "_2-1-介绍性案例、研究"
        },
        {
          "level": 3,
          "title": "案例研究：Privasea",
          "slug": "案例研究-privasea"
        },
        {
          "level": 3,
          "title": "案例研究：多尔萨",
          "slug": "案例研究-多尔萨"
        },
        {
          "level": 3,
          "title": "案例研究 LoverGPT",
          "slug": "案例研究-lovergpt"
        },
        {
          "level": 2,
          "title": "2.2 人工智能与加密货币互相帮助",
          "slug": "_2-2-人工智能与加密货币互相帮助"
        },
        {
          "level": 2,
          "title": "2.3 产品 定位",
          "slug": "_2-3-产品-定位"
        },
        {
          "level": 2,
          "title": "2.4 瓶颈",
          "slug": "_2-4-瓶颈"
        },
        {
          "level": 2,
          "title": "2.5 评估实用性",
          "slug": "_2-5-评估实用性"
        },
        {
          "level": 2,
          "title": "2.6 评估 向上",
          "slug": "_2-6-评估-向上"
        },
        {
          "level": 2,
          "title": "2.7 了解复杂的产品",
          "slug": "_2-7-了解复杂的产品"
        }
      ]
    },
    {
      "title": "!BeWater",
      "frontmatter": {},
      "regularPath": "/zh/aixcrypto/chapter5.html",
      "relativePath": "zh/aixcrypto/chapter5.md",
      "key": "v-07891f18",
      "path": "/zh/aixcrypto/chapter5.html",
      "headers": [
        {
          "level": 2,
          "title": "TODO",
          "slug": "todo"
        },
        {
          "level": 3,
          "title": "TODO",
          "slug": "todo-2"
        }
      ]
    },
    {
      "title": "大创意",
      "frontmatter": {},
      "regularPath": "/zh/aixcrypto/chapter2.html",
      "relativePath": "zh/aixcrypto/chapter2.md",
      "key": "v-8f3ae458",
      "path": "/zh/aixcrypto/chapter2.html",
      "headers": [
        {
          "level": 2,
          "title": "3.1 加密货币与 Deepfake 世界末日",
          "slug": "_3-1-加密货币与-deepfake-世界末日"
        },
        {
          "level": 3,
          "title": "3.1.1\t它们是如何成为问题的？",
          "slug": "_3-1-1它们是如何成为问题的"
        }
      ]
    },
    {
      "title": "!BeWater",
      "frontmatter": {},
      "regularPath": "/zh/aixcrypto/chapter4.html",
      "relativePath": "zh/aixcrypto/chapter4.md",
      "key": "v-34c460d8",
      "path": "/zh/aixcrypto/chapter4.html",
      "headers": [
        {
          "level": 2,
          "title": "TODO",
          "slug": "todo"
        },
        {
          "level": 3,
          "title": "TODO",
          "slug": "todo-2"
        }
      ]
    },
    {
      "title": "!BeWater",
      "frontmatter": {},
      "regularPath": "/zh/aixcrypto/chapter6.html",
      "relativePath": "zh/aixcrypto/chapter6.md",
      "key": "v-12d91154",
      "path": "/zh/aixcrypto/chapter6.html",
      "headers": [
        {
          "level": 2,
          "title": "TODO",
          "slug": "todo"
        },
        {
          "level": 3,
          "title": "TODO",
          "slug": "todo-2"
        }
      ]
    },
    {
      "title": "AIxCrypto 报告",
      "frontmatter": {},
      "regularPath": "/zh/aixcrypto/introduction.html",
      "relativePath": "zh/aixcrypto/introduction.md",
      "key": "v-64aad5b4",
      "path": "/zh/aixcrypto/introduction.html",
      "headers": [
        {
          "level": 2,
          "title": "第 1 部分：核心框架核心框架",
          "slug": "第-1-部分-核心框架核心框架"
        },
        {
          "level": 2,
          "title": "第 2 部分：重要理念",
          "slug": "第-2-部分-重要理念"
        },
        {
          "level": 2,
          "title": "第 3 部分：挑战与机遇",
          "slug": "第-3-部分-挑战与机遇"
        },
        {
          "level": 2,
          "title": "第 4 部分：展望",
          "slug": "第-4-部分-展望"
        }
      ]
    },
    {
      "title": "BeWater 使用指南（参赛者版）",
      "frontmatter": {},
      "regularPath": "/zh/guide/",
      "relativePath": "zh/guide/README.md",
      "key": "v-1518f912",
      "path": "/zh/guide/",
      "headers": [
        {
          "level": 2,
          "title": "第一步：注册和完善信息",
          "slug": "第一步-注册和完善信息"
        },
        {
          "level": 2,
          "title": "第二步：浏览赛事",
          "slug": "第二步-浏览赛事"
        },
        {
          "level": 2,
          "title": "第三步：报名参赛",
          "slug": "第三步-报名参赛"
        },
        {
          "level": 2,
          "title": "第四步：赛事管理",
          "slug": "第四步-赛事管理"
        },
        {
          "level": 2,
          "title": "Q&A",
          "slug": "q-a"
        }
      ]
    },
    {
      "title": "快速上手",
      "frontmatter": {},
      "regularPath": "/zh/guide/getting-started.html",
      "relativePath": "zh/guide/getting-started.md",
      "key": "v-7efe7a38",
      "path": "/zh/guide/getting-started.html",
      "headers": [
        {
          "level": 2,
          "title": "TODO",
          "slug": "todo"
        },
        {
          "level": 3,
          "title": "TODO",
          "slug": "todo-2"
        }
      ]
    }
  ],
  "themeConfig": {
    "logo": "/logo.png",
    "docsDir": "bewater-docs/docs/docs",
    "editLinks": false,
    "lastUpdated": false,
    "algolia": null,
    "smoothScroll": true,
    "sidebarDepth": 2,
    "locales": {
      "/": {
        "label": "English",
        "selectText": "Languages",
        "ariaLabel": "Select language",
        "nav": [
          {
            "text": "Guides",
            "link": "/guide/"
          }
        ],
        "sidebar": {
          "/guide/": [
            {
              "title": "Guides",
              "collapsable": false,
              "children": [
                ""
              ]
            }
          ]
        }
      },
      "/zh/": {
        "label": "简体中文",
        "selectText": "选择语言",
        "ariaLabel": "选择语言",
        "nav": [
          {
            "text": "使用指南",
            "link": "/zh/guide/"
          }
        ],
        "sidebar": {
          "/zh/guide/": [
            {
              "title": "使用指南",
              "collapsable": false,
              "children": [
                ""
              ]
            }
          ],
          "/zh/aixcrypto/": [
            {
              "title": "1. 导言",
              "collapsable": true,
              "children": [
                "introduction"
              ]
            },
            {
              "title": "2. 人工智能 x 密码的核心框架",
              "collapsable": true,
              "children": [
                "chapter1"
              ]
            },
            {
              "title": "3. 大创意",
              "collapsable": true,
              "children": [
                "chapter2"
              ]
            },
            {
              "title": "4. 建设者的机遇",
              "collapsable": true,
              "children": [
                "chapter3"
              ]
            },
            {
              "title": "A.\t附录：机器学习如何工作？",
              "collapsable": true,
              "children": [
                "chapter4"
              ]
            },
            {
              "title": "B.\t附录：ML 面临的挑战",
              "collapsable": true,
              "children": [
                "chapter5"
              ]
            },
            {
              "title": "C.\t附录：展望",
              "collapsable": true,
              "children": [
                "chapter6"
              ]
            }
          ]
        }
      }
    }
  },
  "locales": {
    "/": {
      "lang": "en-US",
      "title": "BeWater Docs",
      "description": "A SOP framework for our business clients to host professional online and offline challenges to build their ecosystem.",
      "path": "/"
    },
    "/zh/": {
      "lang": "zh-CN",
      "title": "BeWater 文档",
      "description": "Web3 创新平台",
      "path": "/zh/"
    }
  }
}